services:
  - type: web
    name: compiler-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PISTON_API_URL
        value: https://emkc.org/api/v2/piston
